---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  name: hotrod
  labels:
    app: hotrod
spec:
  ports:
    - port: 8080
  selector:
    app: hotrod
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: observability
  labels:
    app: hotrod
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: hotrod
      tier: frontend
  template:
    metadata:
      labels:
        app: hotrod
        tier: frontend      
    spec:
      containers:
      - image: jaegertracing/example-hotrod:latest
        name: hotrod
        env:
        - name: JAEGER_AGENT_HOST
          value: localhost
        - name: JAEGER_AGENT_PORT
          value: '6831'
        ports:
        - containerPort: 8080
          name: hotrod