apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udaconnect-ingress
  # annotations:
  #   cert-manager.io/cluster-issuer: <%= issuer_provider %>-<%= cluster_name %>
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "jaeger.10.0.0.12.sslip.io"
      http:
        paths:
          - pathType: Prefix
            path: /prometheus/(.*)
            backend:
              service: 
                name: kind-p-prometheus-server
                port:
                  number: 80
          - pathType: Prefix
            path: /grafana/(.*)
            backend:
              service: 
                name: kind-g-grafana
                port:
                  number: 3000
          - pathType: Prefix
            path: /(.*)
            backend:
              service: 
                name: kind-j-jaeger-query
                port:
                  number: 16686